#!/usr/bin/perl
#
# gendraft
#
# Generates a mdwn draft file ready to be edited.
#
# Copyright © 2015-2016 Guillem Jover <guillem@hadrons.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

use strict;
use warnings;

use UUID qw(uuid);
use File::Path qw(make_path);

die "Usage: $0 <root> <name>\n" if @ARGV < 2;

my $root = $ARGV[0];
my $name = $ARGV[1];
my $uuid = uuid();

my $dirname = "$root/drafts/";
my $basename = ($name =~ tr/A-Z /a-z-/r);
my $filename = "$dirname/$basename.mdwn";

make_path($dirname);

open my $fh, '>', $filename or die "cannot open filename $filename: $!";

print { $fh } "Title: $name\n";
print { $fh } "Tags: draft\n";
print { $fh } "Date: %UNPUBLISHED%\n";
print { $fh } "Uuid: $uuid\n";
print { $fh } "\n";

close $fh or die "cannot close filename $filename: $!";

1;
