#!/usr/bin/perl
#
# genmdwn
#
# Generates a mdwn template file ready to be edited.
#
# Copyright © 2015 Guillem Jover <guillem@hadrons.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

use strict;
use warnings;

use POSIX qw(strftime);
use UUID qw(uuid);

my $date = strftime('%F', localtime);
my $uuid = uuid();

print "Title: \n";
print "Tags: \n";
print "Date: $date\n";
print "Uuid: $uuid\n";

1;
