#!/usr/bin/perl
#
# news2tmpl
#
# Convert a news to a genwebsite template.
#
# Copyright © 2002-2004, 2015, 2017  Guillem Jover <guillem@hadrons.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#

use warnings;
use strict;

use Template;

my $filename = $ARGV[0];

$, = ' ';		# set output field separator
$\ = "\n";		# set output record separator

my $max_recent = 8;
my $recent = 0;
my $entry = 0;

my @news;
my $news;

exit 0 if not -e $filename;

open my $infile, $filename or die "Cannot open $filename: $!";

while (<$infile>) {
    # Strip record separator.
    chomp;

    if (/^\d{4}-\d{2}-\d{2}/) {
	if ($recent > $max_recent) {
	    last;
	} else {
	    $recent++;
	}
	if ($entry) {
	    push @news, $news;
	    $news = {};
	}
	$entry = 1;
	$news->{title} = $_;
	$news->{text} = '';
	next;
    }

    # Remove heading tab.
    s/^\t/ /;

    if (/\.$/) {
	$news->{text} .= $_;
	$news->{text} .= '<br />';
	next;
    }

    $news->{text} .= $_;
}

close $infile;

my $tmplfile = 'site/html-news.tmpl';
my %tmplopts = (
    INTERPOLATE => 1,
    INCLUDE_PATH => 'site:.',
);
my $tmpl = Template->new(%tmplopts);

my $params = {
  news_entries => \@news,
};

$tmpl->process($tmplfile, $params)
    or die "error: $tmplfile: " . $tmpl->error() . "\n";

1;
