#!/usr/bin/perl
#
# patches2wml patchdir
#
# $Id$
#
#	Generates a wml list of patches in rfc822 format from patchdir.
#	The patch title is the patch filename with the patchdir stripped.
#
# Copyright (C) 2003, 2004 Guillem Jover <guillem@hadrons.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#

use warnings;
use strict;

my $scriptdir = "~/web/wml/scripts";
my $patchdir = $ARGV[0];

my @status_list = ("not_applied", "applied", "fixed", "unknown");

foreach (@status_list) {
  my $status_note = $_;

  $status_note =~ tr/_/ /;

  print "{#patch_toc#:<toc-entry href=\"#$_\">$status_note</toc-entry>:##}\n";
  print "{#patch_list#:\n";
  print "<div class=\"patches_$_\">\n";
  print "  <h2><a id=\"$_\">Patches $status_note</a></h2>\n";
  print "  {#patch_list_$_#}\n";
  print "</div>\n";
  print "<hr />\n";
  print ":##}\n";
}

open CMD, "find $patchdir/ -name '*.patch' | sort |";
while (<CMD>) {
  chomp;

  my $patch = $_;
  $patch =~ s/^\.\///;
  my $title = $_;
  $title =~ s/^$patchdir\///;

  system "$scriptdir/patch2wml '$patch' '$title'";
}
close CMD;

