#!/bin/bash
#
# htms2html
#
#	$Id$
#
#	Convert HTMS to Std HTML
#
# Copyright (C) 2001-2003 Guillem Jover <guillem@hadrons.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#

error ()
{
	echo "htms2html: $2" >&2
	exit $1
}

input=$1

[ -f "$input" ] || error 1 "input file does not exist"

BIN_DIR=$(dirname $0)
STYLE_DIR=$BIN_DIR
STYLE_LIST=$(ls $STYLE_DIR/style.*)

DEFAULT_STYLE="plain"

if [ -z "$STYLE" ]; then
	STYLE=$DEFAULT_STYLE
else
	echo $STYLE_LIST | grep $STYLE > /dev/null 2>&1
	if [ $? != 0 ]; then
		error 2 "specified style is not available"
	fi
fi

# Insert ChangeLog if it exists
changelog_file=$(basename $input .htms).news

(
if [ -f $changelog_file ]; then
	tmp=/tmp/changelog2htms.$$
	$BIN_DIR/changelog2htms < $changelog_file > $tmp
	sed -n "/<changelog-file>/!p;/<changelog-file>/r $tmp" < $input
	rm -f $tmp
else
	cat $input
fi
) |

# Apply style
sed -f $STYLE_DIR/style.common | sed -f $STYLE_DIR/style.$STYLE

