#!/bin/bash
#
# patch2htms language directory
#
# $Id: patch2htms,v 1.2 2003/04/23 18:27:12 guillem Exp $
#
#	generates an htms file from a list of patches in rfc822 format
#
# Copyright (C) 2003 Guillem Jover <guillem@hadrons.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#

PROGRAM=patch2htms

SCRIPTDIR=$(dirname $0)
PATCHDIR=$1
BUILDDIR=${2:-$(pwd)}

iso-date ()
{
	date -Iseconds | tr 'T' ' '
}

parse_rfc822 ()
{
	filename=$1
	title="$(echo $filename|sed -e 's/_/ /g; s/\.patch$//')"

	echo "    <patch-title href=\"$filename\">$title</patch-title>"
	echo "    <patch-description>"

	IFS=""
	prev_entry=empty
	cat $filename | while read line
	do
		line=`echo "$line"|sed -e 's%[[:space:]]*$%%' \
			-e 's%<%\&lt;%g; s%>%\&gt;%g'`

		# End of RFC822 header data
		if [ ${#line} -eq 0 ]; then break; fi

		# Don't show Author
#		if expr $line : "Author" > ; then break; fi

		if [ "${line:0:1}" == " " ]
		then
			if [ $prev_entry = "field" ]
			then
				echo " <br />"
			fi

			entry="$(echo "$line"|sed -e 's%^ \.%<br />%; s%\.$%.<br />%')"
			echo "    $entry"
			prev_entry=description
		else
			entry="$(echo "$line"|sed -e 's%^%<b>%; s%^[^:]*%&</b>%')"
			if [ $prev_entry != "empty" ]; then
				echo "</li>"
			fi
			printf "      <li>$entry"
			prev_entry=field
		fi
	done

	echo "      </li>"
	echo "    </patch-description>"
	echo
}

generate_body ()
{
	for f in `find $PATCHDIR -name '*.patch'`
	do
		echo $f
		parse_rfc822 $f >> patches.body.htms
	done
}

generate_htms ()
{
	cat > patches.htms <<-HEADER
	<sgml-doctype>
	<html>
	<head>
	  <content-meta>
	  <title>Patches</title>
	  <language-meta>
	  <common-meta>
	  <meta name="Generator" content="rfc822_to_html \$Revision: 1.2 $ ">
	  <common-style>
	</head>
	<body>
	  <page-index>
	    <index-entry href="./">Home</index-entry>
	  </page-index>
	
	  <page-contents>
	    <h1>Patches List</h1>
	
	    <p>
	    All patches here are not applied yet. Patches applied will be
	    removed.
	    </p>
	HEADER

	cat patches.body.htms >> patches.htms

	cat >> patches.htms <<-FOOTER
	  </page-contents>
	
	  <page-separator>
	
	  <page-footer>
	  Automatically generated on: $(iso-date)
	  </page-footer>
	
	</body>
	</html>
	FOOTER
}

#
# Main program
#

cd $BUILDDIR

generate_body
generate_htms

rm patches.body.htms

exit 0

