#!/bin/bash
#
# patch2htms patchdir [builddir] [basename]
#
# $Id: patch2htms,v 1.15 2003/11/11 05:17:53 guillem Exp $
#
#	Generates a htms file from a list of patches in rfc822 format,
#	uses builddir to output all temp files and the result, and patchdir
#	is the dir from where the relative paths to patches is taken.
#	The only restriction is that patchdir should be a subdirectory of
#	builddir.
#
# Copyright (C) 2003 Guillem Jover <guillem@hadrons.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#

PROGRAM=patch2htms

SCRIPTDIR=$(dirname $0)
PATCHDIR=$1
BUILDDIR=${2:-$PATCHDIR}
BASENAME=${3:-patches}

FIELDS_EXCLUDED="Author"
STATUS_LIST="not-applied applied fixed"

iso-date ()
{
	date -Iseconds | tr 'T' ' '
}

parse_rfc822 ()
{
	filename=$1
	title="$filename"

	echo "    <patch-title href=\"$filename\">$title</patch-title>"
	echo "    <patch-description>"

	REAL_IFS=$IFS
	IFS=
	prev_entry=empty
	cat $filename | while read line
	do
		line=`echo "$line" | sed -e 's%[[:space:]]*$%%' \
			-e 's%<%\&lt;%g; s%>%\&gt;%g'`

		# End of RFC822 header data
		if [ ${#line} -eq 0 ]; then break; fi

		# Split the line
		LOCAL_IFS=$IFS
		IFS=":"
		set -- $line
		IFS=$LOCAL_IFS

		field="$1"
		shift
		content="$@"

		IFS=$REAL_IFS
		# Don't show excluded fields
		for excluded in $FIELDS_EXCLUDED
		do
			if [ "$field" = "$excluded" ]; then continue; fi
		done
		IFS=

		if [ "$field" = "Status" ]
		then
			field_status=$(echo "$content" | \
			               tr '[:upper:] ' '[:lower:]-')
			echo $field_status >&2
		fi

		if [ "${line:0:1}" == " " ]
		then
			if [ $prev_entry = "field" ]
			then
				echo " <br />"
			fi

			entry="$(echo "$line" | \
			         sed -e 's%^ \.%<br />%; s%[.:]$%&<br />%')"
			echo "      $entry"
			prev_entry=description
		else
			entry="<b>$field: $content</b>"
			if [ $prev_entry != "empty" ]; then
				echo "</li>"
			fi
			printf "      <li>$entry"
			prev_entry=field
		fi
	done
	IFS=$REAL_IFS

	echo "      </li>"
	echo "    </patch-description>"
	echo
}

generate_body ()
{
	for f in `find $PATCHDIR -name '*.patch' | sed -e 's/^\.\///'`
	do
		parse_rfc822 $f > $BASENAME.entry.htms 2> $BASENAME.status
		Status=$(cat $BASENAME.status)
		echo $f: $Status
		cat $BASENAME.entry.htms >> $BASENAME.body$Status.htms
	done
}

generate_htms ()
{
	cat > $BASENAME.htms <<-HEADER
	<sgml-doctype>
	<html>
	<head>
	  <content-meta>
	  <title>Patches</title>
	  <language-meta>
	  <common-meta>
	  <meta name="Generator" content="patch2htms \$Revision: 1.15 $ ">
	  <common-style>
	</head>
	<body>
	  <page-index>
	    <index-entry href="./">Home</index-entry>
	
	    <index-separator>
	
	HEADER

	for Status in $STATUS_LIST
	do
		Status_Note=$(echo $Status | tr '-' ' ')
		cat >> $BASENAME.htms <<-HEADER
		    <index-entry href="#$Status">$Status_Note</index-entry>
		HEADER
	done

	cat >> $BASENAME.htms <<-HEADER
	  </page-index>
	
	  <page-contents>
	    <h1>Patches List</h1>
	
	HEADER

	for Status in $STATUS_LIST
	do
		if [ -e $BASENAME.body-$Status.htms ]
		then
			Status_Note=$(echo $Status | tr '-' ' ')
			cat >> $BASENAME.htms <<-SECTION
			    <h2><a id="$Status">Patches $Status_Note</a></h2>
			SECTION
			cat $BASENAME.body-$Status.htms >> $BASENAME.htms
		fi
	done

	if [ -e $BASENAME.body.htms ]
	then
		cat >> $BASENAME.htms <<-SECTION
		    <hr>
		    <h2><a id="unkwnown">Patches unkwnown status</a></h2>
		SECTION
		cat $BASENAME.body.htms >> $BASENAME.htms
	fi

	cat >> $BASENAME.htms <<-FOOTER
	  </page-contents>
	
	  <page-separator>
	
	  <page-footer>
	  Automatically generated on: $(iso-date)
	  </page-footer>
	
	</body>
	</html>
	FOOTER
}

#
# Main program
#

if [ "$PATCHDIR" = "$BUILDDIR" ]
then
	PATCHDIR="."
fi

cd $BUILDDIR

generate_body
generate_htms

rm -f $BASENAME.body* $BASENAME.entry* $BASENAME.status

exit 0

