#!/usr/bin/perl
#
# patches2wml patchdir
#
# $Id$
#
#	Generates a wml file from a list of patches in rfc822 format,
#	uses builddir to output all temp files and the result, and patchdir
#	is the dir from where the relative paths to patches is taken.
#	The only restriction is that patchdir should be a subdirectory of
#	builddir.
#
# Copyright (C) 2003, 2004 Guillem Jover <guillem@hadrons.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#

use warnings;
use strict;

my $scriptdir = "~/web/scripts";
my $patchdir = $ARGV[0];

my @status_list = ("not_applied", "applied", "fixed", "unknown");

foreach (@status_list) {
  my $status_note = $_;

  $status_note =~ tr/_/ /;

  print "{#patch_toc#:<toc-entry href=\"#$_\">$status_note</toc-entry>:##}\n";
  print "{#patch_list#:{#patch_list_$_#}:##}\n";
  print "{#patch_list_$_#:\n";
  print "<hr />\n";
  print "<h2><a id=\"$_\">Patches $status_note</a></h2>\n";
  print ":##}\n";
}

open CMD, "find $patchdir/ -name '*.patch' | sort |";
while (<CMD>) {
  chomp;

  my $patch = $_;
  $patch =~ s/^\.\///;
  my $title = $_;
  $title =~ s/^$patchdir\///;

  system "$scriptdir/patch2wml '$patch' '$title'";
}
close CMD;

